# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d64d2d4e-4397-487c-adf7-cbfa66eb58ef";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/4742536a-1b0d-4a4e-9d15-c03b579e0b94";

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/d64d2d4e-4397-487c-adf7-cbfa66eb58ef";
      fsType = "btrfs";
      options = [ "subvol=nix" "noatime"];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/d64d2d4e-4397-487c-adf7-cbfa66eb58ef";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/d64d2d4e-4397-487c-adf7-cbfa66eb58ef";
      fsType = "btrfs";
      options = [ "subvol=var" ];
    };

  fileSystems."/.swapvol" =
    { device = "/dev/disk/by-uuid/d64d2d4e-4397-487c-adf7-cbfa66eb58ef";
      fsType = "btrfs";
      options = [ "subvol=swap" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4E36-5A02";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ { device = "/.swapvol/swapfile"; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s20f0u3u2.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
